|------------+----------------------------------------------------------|
| wiki       | https://en.wikipedia.org/wiki/OpenSMTPD                  |
| home       | https://www.opensmtpd.org/                               |
| arch       | https://wiki.archlinux.org/title/OpenSMTPD               |
| source(C)  | https://github.com/OpenSMTPD/OpenSMTPD                   |
| awk filter | https://github.com/jirutka/opensmtpd-filter-rewrite-from |
|------------+----------------------------------------------------------|

- Public release on 2013

- Both server and client side implementations of SMTP
  - server: accept messages coming from the network or local socket and put it to the queue
  - client: taking a message from the queue and forwarding it

- no shared memory, only IPC communication

- is a multi-process daemon
  - smtpd (only process under root user)
  - lookup (not chroot)
  - control
  - klondike
  - queue
  - scheduler
  - pony express

- 14 https://web.archive.org/web/20220701225113/https://blog.corrupted.io/2014/06/09/OpenSMTPD-virtual-users-with-sqlite.html
- 15 https://raysnotebook.info/computing/email-opensmtpd.html
- 15 https://frozen-geek.net/openbsd-email-server-1/
- 16 https://frozen-geek.net/openbsd-email-server-2/
- 16 https://web.archive.org/web/20160126030038/https://www.openbsd.org/opensmtpd/faq/example1.html
- 17 https://web.archive.org/web/20170715133140/https://blog.cagedmonster.net/opensmtpd-and-dovecot-under-openbsd-with-mysql-support-and-spamd/
- 18 https://battlepenguin.com/tech/openbsd-spampd-and-the-startup-bug/
- 18 https://poolp.org/posts/2018-11-03/opensmtpd-released-and-upcoming-filters-preview/
- 18 https://poolp.org/posts/2018-05-21/switching-to-opensmtpd-new-config/
- 18 https://github.com/lattera/articles/blob/master/opsec/2018-05-08_torified_mta/article.md
- 19 https://poolp.org/posts/2019-07-27/july-2019-report-tons-of-smtpd-work-mostly/
- 19 https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/
- 19 https://nicolascarpi.github.io/openbsd/2019/04/03/openbsd-mail-server.html
- 20 https://poolp.org/posts/2020-01-30/opensmtpd-advisory-dissected/
- 20 https://github.com/poolpOrg/OpenSMTPD-book
  - certificate -> cert
  - mask-source -> mask-src
  - one line rules -> multiple lines rule
- 20 https://dev.to/nabbisen/opensmtpd-how-to-receive-emails-sent-by-remote-hosts-to-os-local-users-48oj
     https://dev.to/nabbisen/rspamd-installation-and-opensmtpd-configuration-on-it-on-openbsd-1p6i
     https://dev.to/nabbisen/rspamd-monitoring-with-openbsd-relayd-486m
     https://dev.to/nabbisen/dkim-migration-rpamd-instead-of-dkimproxy-out-on-openbsd-opensmtpd-2k6m
- 20 https://www.ctrl.blog/entry/systemd-opensmtpd-hardening.html
- 20 https://web.archive.org/web/20200408175322/https://prefet.ch/blog/2020/email-server/
- 20 https://www.theregister.com/2020/01/30/openbsd_mail_bug/
- 20 https://very.busted.systems/Simple-OpenSMTPD-filter-example-in-awk
- 20 https://karchnu.fr/posts/2020-09-17-certificate-smtp-imap-antispam.html
- 21 http://code.jeremyevans.net/2021-07-29-running-my-own-email-server.html
- 21 https://battlepenguin.com/tech/upgrading-opensmtpd-6.3-and-running-e-mail-in-docker/
- 21 https://kfv.medium.com/my-opensmtpd-setup-on-freebsd-ed57c052fbc1
- 22 https://docs.vultr.com/an-openbsd-e-mail-server-using-opensmtpd-dovecot-rspamd-and-rainloop
- 22 https://x61.sh/log/2022/10/20221027T115439-rspamd-dashboard.html
- 23 https://palant.info/2023/03/08/converting-incoming-emails-on-the-fly-with-opensmtpd-filters/
- 23 https://www.bsdhowto.ch/mxpop3.html
- 23 https://wiki.ircnow.org/index.php?n=Opensmtpd.Configure?from=Openbsd.Opensmtpd
- 23 https://kilabit.info/journal/2023/replacing_postfix_with_opensmtpd/
- 23 https://draft.websteading.net/smtpd/


- video: Mail with OpenSMTPD, fdm, and mblaze! https://www.youtube.com/watch?v=5YS8RPC4zwc&t=23s
- video: opensmptd filter in ruby https://www.youtube.com/watch?v=LWkatTvSPpY
  - rewrite subject line


* TODO Video: 23 | Filtering Mail with Ruby!

https://www.youtube.com/watch?v=LWkatTvSPpY

- rewrite subject
- $ man smtpd-filters

- Characteristics
  - standalone processes
  - do not share memory with ~smtpd~ process
  - expected to run an infinite loop
  - reading from STDIN
  - responding to STDOUT
  - logging to STDERR
  - *must not block IO* (standard read/write in ruby is blocking)

- API relies on 2 streams
  - report stream: 1 way stream to notify of new things
  - filter stream: 2 way stream

** Protocol

- at initialization, receives
  #+begin_src
    config|smtpd-version|6.6.1
    config|smtp-session-timeout|300
    config|subsystem|smtp-in
    config|ready
  #+end_src

- at initialization, it should send after
  #+begin_src config
    register|report|smtp-in|link-connect
    register|ready
  #+end_src

* TODO Video: 20 | OpenSMTPD over the clouds the story of an HA setup | Giovanni Bechis
https://www.youtube.com/watch?v=y6DLZkAT4Bg

- postfix/spamassasin/amavis-new/courier-imap
  to
  opensmtpd

- On '19 filters were added to opensmtpd

- pf + relayd for load balancer
  #+NAME: relayd config
  #+begin_src conf
  mx0_pub="1.2.3.4"
  mx0_priv="10.0.0.4"
  mx1_priv="10.0.0.5"

  table <mx0> { $mx0_priv }
  table <fallback-mx0> { $mx1_priv }

  redirect mx0-smtp {
    listen on $mx0_pub port smtp \
      interface $if_pub sticky-address

    pftag RELAYD

    forward to <mx0> check tcp
    forward to <fallback-mx0> check tcp
  }
  #+end_src

- MySQL master-master replica to share databases
  #+begin_src
    [mysqld]
    server-id=1

    binlog-do-db = dbispconfig
    binlog-do-db = sogo

    replicate-do-db = dbispconfig
    replicate-do-db = sogo

    auto_increment_increment = 2
    auto_increment_offset    = 1
  #+end_src

- MySQL setup replica
  #+begin_src
    > CHANGE MASTER TO MASTER_HOST='10.0.0.5', \
      MASTER_PORT=3306, \
      MASTER_USER='replica', \
      MASTER_PASSWORD='changeme', \
      MASTER_LOG_FILE='slave-bin.000831', \
      MASTER_LOG_POS=341, \
      MASTER_CONNECT_RETRY=10;

    > CHANGE MASTER TO master_use_gtid=slave_pos;
  #+end_src

- shared NFS storage

- sogo for calendar service

- smtpd
  #+begin_src
    pki mx.domain.tld cert "/etc/.../fullchain.pem"
    pki mx.domain.tld key  "/etc/.../privkey.pem"

    table aliases file:/etc/mail/aliases

    table vusers mysql:/etc/mail/mysql.conf
    table vdomains mysql:/etc/mail/mysql.conf
    table valiases mysql:/etc/mail/mysql.conf
    table credentials mysql:/etc/mail/mysql.conf
  #+end_src

- smtpd - mysql.conf
  #+begin_src
    host     127.0.0.1
    username ispcsrv6
    password xxx
    database dbispconfig

    # Alias lookup query
    query_alias SELECT destination FROM mail_valias \
                 WHERE source=?

    # Domain lookup query
    query_domain SELECT domain FROM mail_domain \
                  WHERE domain=?;

    # User lookup query - user cannot be the email address, so REPLACE (!?
    query_userinfo SELECT uid,id,maildir \
                     FROM mail_user
                    WHERE REPLACE(login, '@', '_')=? \
                      AND server_id=6;

    # Credentials lookup query
    query_crendentials SELECT login, password \
                         FROM mail_user
                        WHERE login=?
                          AND disablesmtp='n';
  #+end_src

- smtpd - antispam - define filters
  #+begin_src
    filter check_dyndns phase connect match rdns \
      regex { '.*\.dyn\..*', '.*\.dsl\..*' } \
      disconnect "550 no residential connections"
    filter check_rdns phase connect match !rdns \
      disconnect "550 no rDNS available"
    filter "dkimsign" proc-exec "filter-dkimsign \
           -d domain.tld -s dkim \
           -k /etc/mail/dkim/key.pem" \
           user _dkimsign group _dkimsign
    filter "spamassasin" proc-exec "filter-spamassasin"
  #+end_src

- smtpd - antispam - apply filters
  #+begin_src
    listen on socket filter "dkimsign"
    listen on lo0 filter "dkimsign"
    listen on egress filter { check_dyndns, check_rdns, spamassassin } \
      tls pki mx.domain.tld
    listen on egress filter { check_dyndns, check_rdns, spamassassin } \
      smtps pki mx.domain.tld
    listen on egress port submission filter "dkimsign" \
      tls auth <credentials> pki mx.domain.tld
  #+end_src

- filter-clamav wasn't production ready at that point
- 22:00

* TODO Video: 13 | OpenSMTPD, current state of affairs                | Gilles Chehade

https://www.youtube.com/watch?v=p0S1bbO-h0k

- Gilles is the creator of OpenSMTPD

- SMTP
  - is only a way to move mail between machines, is not for retrieve it.
  - relies heavily on the DNS protocol (MX)
  - to goal of a MX is to route msg closer to the destination
  - it only sees 1(one) node ahead
  - RFC imposes responsability over the msgs
    - you are not allowed to lose a msg that you accepted
    - if you can't relay, the sender must be ack
    - each MX has an interest in getting message out of it way fast
    - transactional protocol, accepted message is a commit

- code example of how to implement your own backend in C

- 28:00 dev...
* TODO Video: 13 | OpenSMTPD: We deliver!                             | Eric Faurot

- video https://www.youtube.com/watch?v=7kaSyQYYGRQ
- paper https://2013.asiabsdcon.org/papers/abc2013-P4B-paper.pdf

- conf
  - syntax inpired by pf.conf
  - first match wins

- /var/spool/smtpd/queue

- /usr/sbin/smtpctl
  - local enqueue (sendmail)
  - queue inspection
  - mail remove
  - pause/resume
  - stats
  - monitor activity
  - talks through a unix socket

- IPC between spawned process happens through imsg(3) protocol

26:00

** Examples

- Example: minimalist setup
  #+begin_src
  listen on lo0

  table aliases db:/etc/mail/aliases.db

  accept for local alias <aliases> deliver to mbox
  accept for any relay
  #+end_src

- Example: primary domain
  #+begin_src
    listen on egress

    table aliases db:/etc/mail/aliases.db

    accept from any for domain "example.org" \
                     alias <aliases> deliver to mbox
    accept for local alias <aliases> deliver to mbox
    accept for any relay
  #+end_src

- Example: using a smarthost
  #+begin_src
    listen on lo0

    table secrets file:/etc/mail/secrets
    table aliases db:/etc/mail/aliases.db

    accept for local alias <aliases> deliver to mbox
    accept for any relay \
      via smtps+auth://label@smtps.my.isp \
      auth <secrets>
  #+end_src

- Example: backup server
  #+begin_src
    listen on egress

    table poolp { poolp.org, opensmtpd.org }

    accept for local deliver to mbox

    accept from any for domain example.org relay \
      backup mx4.example.org

    accept from any for domain <poolp> relay \
      backup mx2.poolp.org
  #+end_src

- Example: signing outgoing mail with dkimproxy
  #+begin_src
    listen on lo0
    listen on lo0 port 10029 tag DKIM

    accept for local deliver to mbox
    accept tagged DKIM for any relay
    accept for any relay via smtp://127.0.0.1:10028
  #+end_src

- Example: authenticating relay
  #+begin_src
    listen on egress port submission tls \
      certificate my.cert auth

    accept from any for domain "opensmtpd.org" \
      deliver to maildir

    accept for any relay
  #+end_src

- Example: deliver to virtual users
  #+begin_src
    listen on egress

    table usr { "alice" = "100:100:/var/vusers/alice",
                "bob" = "100:100:/var/vusers/bob" }

    accept from any for domain "wonderland.org" \
      userbase <usr> deliver to maildir

    accept for any relay
  #+end_src
