name: trigger notes site build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # See: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
      - name: curl azimut/notes/actions/workflows/main.yml
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGERHAPPY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/azimut/notes/actions/workflows/main.yml/dispatches \
            --data '{"ref": "master"}'
